---
title: "About me"

date: "`r format(Sys.time(), '%d %B, %Y')`"

output: html_document
---

## Beni Cakitaki
#### Senior Researcher at the Centre for Higher Education Equity & Diversity Research (CHEEDR) at La Trobe University

Quantitative researcher at CHEEDR, La Trobe University. Intellectual interests are broad, but include higher education equity, policy, statistics, R, causal inference, Australian history, history of economic thought, unions and collective action, labour markets, and the study of social, and economic inequality. 

Otherwise, I love AFL footy - Western Bulldogs, Taika Waititi films, Stormzy, Elton John, and the All Blacks. 

\         

# __What is this blog about?__

> *I web therefore I am ~~spiderman.~~*


> *Yihui Xie*


Early in 2020 I started reading up on the R package 'blogdown', and came across this talk by [David Robinson](https://resources.rstudio.com/rstudio-conf-2019/the-unreasonable-effectiveness-of-public-work), and this talk by [Yihui Xie](https://resources.rstudio.com/rstudio-conf-2019/pagedown-creating-beautiful-pdfs-with-r-markdown-and-css). Both emphasised the importance of making the stuff you do public by putting it up on a website. Yihui and colleagues created a set of tools that made creating a website incredibly easy for people like me who know a bit of R, but are completely out of their depth with HTML. And integrating ggplot2 graphics seamlessly into a website is super cool. 

I figured there was quite alot of work I was doing that was not quite publication ready, and may never be, but was probably worthwhile to someone in a less pedantic form. This blog is a place for these pieces, and other snippets of what flitter around my head from time to time. 

