---
title: How would rankings from an Australian PBF compare to other conventional rankings?
author: ~
date: '2020-02-06'
slug: how-would-rankings-from-an-australian-pbf-compare-to-other-conventional-rankings
categories: []
tags: []
---

### Australian performance based funding

In a report last year on performance based funding alongside my co-authors Andrew Harvey and Matt Brett, we raised the point that the TEF in the UK could disrupt conventional higher education rankings such as the THE or QS. 

In part this depends on how salient the ranking is on those that make decisions that could be considered competitive, ie potential students. Holding that constant, we found the TEF at the very least did nominally dislodge some of the prevailing hierarchies. 

Since then, the Australian Government has set and implemented performance based funding. So I thought it may be instructive to try and construct a rankings from the metrics, and then compare this to the other conventional rankings systems.

